server:
  port: 8080

spring:
  #Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
 #Database
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${vcap.services.books-postgres-db.credentials.username}
    password: ${vcap.services.books-postgres-db.credentials.password}
    url: jdbc:postgresql://${vcap.services.books-postgres-db.credentials.hostname}:${vcap.services.books-postgres-db.credentials.port}/${vcap.services.books-postgres-db.credentials.dbname}
  #Jackson
  jackson:
    default-property-inclusion: non_null

multitenant:
  defaultTenant: public

logging:
  level:
    com.github.com.github.kaydunovdenis: DEBUG
    com.sap.cloud.sdk: INFO
    root: WARN
# actuator
management:
  endpoints:
    web:
      exposure:
        include: beans,health,httptrace
